Sharma 2021b added
pyrfume/pyrfume-data pull request #103
Opened 2022-04-29 18:38 UTC by TGouldBates

2022-05-02 16:02 UTC, rgerkin requested changes
Unclear how index column in behavior is related to column(s) in odorants and odorless.

2022-05-02 16:02 UTC, rgerkin commented on sharma_2021b/odorless.csv
> +Sr.No.,Name,SMILES,CAS No,Mol. Wt.,Mol. Formula,PubChem,ZINC
Also "PubChem" column name should be changed to match what it is in molecules.csv -- the idea is to be able to link columns by name programatically.

2022-05-03 23:11 UTC, TGouldBates commented on sharma_2021b/manifest.toml
> +ordors.csv = "Full dataset of odor descriptors, compliled from all files in raw/."
I must be dense, but I'm not seeing the typo in that line...

2022-05-04 16:13 UTC, rgerkin commented on sharma_2021b/manifest.toml
> +ordors.csv = "Full dataset of odor descriptors, compliled from all files in raw/."
My bad, it's the next line (ordors).

2022-05-24 14:20 UTC, TGouldBates commented on sharma_2021b/odorless.csv
> +Sr.No.,Name,SMILES,CAS No,Mol. Wt.,Mol. Formula,PubChem,ZINC
After clarifying that odorants.csv and odorless.csv are "raw" data, I'm assuming that you don't want me to change the column headings from the original, but let me know if you still do.

2022-05-24 14:58 UTC, merged