Burton 2022 added
pyrfume/pyrfume-data pull request #107
Opened 2022-06-08 16:56 UTC by TGouldBates

2022-06-08 19:54 UTC, rgerkin requested changes
- Also change CID to a stimulus ID everywhere (see stimuli.csv for details).
- Change behavior1 to use stimulus, subject (now experiment, but with same info, i.e. first column of subjects.csv -- a subject is a hemisphere), roi, dF.

2022-06-08 19:54 UTC, rgerkin commented on burton_2022/manifest.toml
> +"behavior_3.csv" = "Properties of diagnostic odorants that consistently elicit sparse activation but did not meet the cirteria for functional identification. See main.py for full details."
Typo in criteria.

2022-06-08 19:54 UTC, rgerkin commented on burton_2022/stimuli.csv
> +CID,Mouse ID,Conc. (mols/L)
Reorganize to have columns:
"Stimulus", "CID", and "Conc. (mols/L)"
Every unique combination of CID and concentration should have a different stimulus ID (could be a simple concatenation with an underscore, up to a certain number of digits).
Add a row for blank.
Drop Mouse ID.

2022-06-08 19:54 UTC, rgerkin commented on burton_2022/molecules.csv
> +-1,,,,empty
Drop the -1.

2022-06-14 21:59 UTC, TravisGould commented
Changes pushed. Except for re-indexing behavior_2 and 3 which aren't set up
to be compatible with a stimulus index. Can be done with some
restructuring, but would be good first to know if there is any data in
those files that you don't want to actually keep.

On Wed, Jun 8, 2022 at 3:55 PM Richard C Gerkin ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
>    - Also change CID to a stimulus ID everywhere (see stimuli.csv for
>    details).
>    - Change behavior1 to use stimulus, subject (now experiment, but with
>    same info, i.e. first column of subjects.csv -- a subject is a hemisphere),
>    roi, dF.
>
> ------------------------------
>
> In burton_2022/manifest.toml
> <https://github.com/pyrfume/pyrfume-data/pull/107#discussion_r892799686>:
>
> > +extra = ""
> +
> +[raw]
> +"raw/odormappingdata_fullinfo_06_2021.mat" = "All raw data except for odorant concentrations. See main.py for full details."
> +"raw/odormappingdata_simple_05_2022.mat" = "Simplified version of 'fullinfo' .mat file containig deltaF response matrices and odorant concentrations. See main.py for full details."
> +"raw/ID_glom_04_2022.mat" = "Data for functionally-identifiable glomeruli and diagnostic odorants. See main.py for full details."
> +"raw/XXXX_ROIPos.csv" = "X and Y coordinates for the centroids of each ROI (glom) in each experiment XXXX; exported from odormappingdata_fullinfo_06_2021.mat file because Matlab 'table' class is not Python readable."
> +"LICENSE" = ""
> +
> +[processed]
> +"main.py" = "Processing workflow."
> +"molecules.csv" = "Information about odorant molecules used. -1 CID assigned to 'empty' which is the control."
> +"imaging.csv" = "Paths to response maps saved in .csv form for every odorant/mouse combination tested."
> +"behavior_1.csv" = "DeltaF response values of every ROI (glomerulus) for every odorant/mouse tested."
> +"behavior_2.csv" = "Properties of diagnostic odorants with functionally-identified glomeruli. See main.py for full details."
> +"behavior_3.csv" = "Properties of diagnostic odorants that consistently elicit sparse activation but did not meet the cirteria for functional identification. See main.py for full details."
>
> Typo in criteria.
> ------------------------------
>
> In burton_2022/stimuli.csv
> <https://github.com/pyrfume/pyrfume-data/pull/107#discussion_r892802707>:
>
> > @@ -0,0 +1,741 @@
> +CID,Mouse ID,Conc. (mols/L)
>
> Reorganize to have columns:
> "Stimulus", "CID", and "Conc. (mols/L)"
> Every unique combination of CID and concentration should have a different
> stimulus ID (could be a simple concatenation with an underscore, up to a
> certain number of digits).
> Add a row for blank.
> Drop Mouse ID.
> ------------------------------
>
> In burton_2022/molecules.csv
> <https://github.com/pyrfume/pyrfume-data/pull/107#discussion_r892802919>:
>
> > @@ -0,0 +1,188 @@
> +CID,MolecularWeight,IsomericSMILES,IUPACName,name
> +-1,,,,empty
>
> Drop the -1.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pyrfume/pyrfume-data/pull/107#pullrequestreview-1000353101>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMR2YW7R2ODBRMILVF2MYMLVOD3BZANCNFSM5YHHCY6A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-29 19:02 UTC, merged