optical rotation code
pyrfume/pyrfume-data pull request #68
Opened 2022-02-02 20:18 UTC by colemanliyah

Extracts optical rotation values from pubchem list of strings where each string is information on one molecule. Currently, the code works to extract the optical rotation values from the raw data file given. But the code can be slightly altered to take in a different data file. 

All that's included in this PR is given in the manifest.toml file.

2022-02-02 23:14 UTC, rgerkin reviewed
See the comments here and also add a molecules.csv (based on piping CIDs through pyrfume.odorants.get_cids and wrapping in a dataframe) and an attributes.csv which actually contain the OPR values (the column name can be "Optical Rotation Angle" or something like that).

2022-02-02 23:14 UTC, rgerkin commented on optical_rotation_scrapping/manifest.toml
> +authors = "Richard R Gerkin, Liyah A Coleman"
My middle initial is C

2022-02-02 23:14 UTC, rgerkin commented on optical_rotation_scrapping/manifest.toml
> +title = "Scrapping optical rotation values from molecules in PubChem"
Make the title describe the data not the process

2022-02-02 23:14 UTC, rgerkin commented on optical_rotation_scrapping/manifest.toml
> +Values were extracted from PubChem
This should have a file name in quotes, then =, then a description in quotes.  Add a bit more in the description (i.e. the heading from which they were extracted).

2022-02-02 23:14 UTC, rgerkin commented on optical_rotation_scrapping/manifest.toml
> +"opticalroation.ipynb" = "notebook for running code"
The file that runs the code to generated the processed data should always be "main.py" or "main.ipynb" for consistency.

The list of molecules should be molecules.py, the list of values should be in properties.py.  This is based on making shot-in-dark loading of these data successful without referring back to the details of the manifest.

2022-02-07 17:58 UTC, rgerkin commented on optical_rotation_scrapping/manifest.toml
> +"attributes.csv" = "dataframe of the scrpped opr values"
Fix typo and capitalize first word of each sentence.

2022-02-07 18:00 UTC, rgerkin requested changes
Please make these fixes.

2022-02-16 00:34 UTC, rgerkin requested changes

2022-02-16 00:34 UTC, rgerkin commented on optical_rotation_scrapping/attributes.csv
> +CIDs,Optical Rotation Angle
First column should be called "CID", not "CIDs"

2022-02-16 00:34 UTC, rgerkin commented on optical_rotation_scrapping/manifest.toml
> +authors = "Richard C Gerkin, Liyah A Coleman"
You should list yourself first.

2022-02-16 00:34 UTC, rgerkin commented on optical_rotation_scrapping/molecules.csv
> +,CID,MolecularWeight,IsomericSMILES,IUPACName,name
The CID column itself should be the index, so you want to set it as the index before you export the csv file (this way it matches the attributes file).  So there shouldn't be a separate integer index (0, 1, 2, ...).

2022-02-16 00:34 UTC, rgerkin commented on optical_rotation_scrapping/raw_data.csv
> +CIDs,Properties,Properties,Properties,Properties,Properties
Change to "CID".  Also why are there 5 columns called "Properties"?  Are there up to 5 strings for each CID?  If so, change them to "Properties1", "Properties2", etc.

2022-02-18 16:34 UTC, rgerkin requested changes
One small change and also please help me understand why there are so many duplicate angles (see comment).

2022-02-18 16:34 UTC, rgerkin commented on optical_rotation_scrapping/attributes.csv
> +,Optical Rotation Angle
Index column name should be "CID", not blank.

2022-02-18 16:34 UTC, rgerkin commented on optical_rotation_scrapping/attributes.csv
>  3032576,+230
Why are there so many CIDs associated with the same rotation angle?  e.g. lines 13-19 below, or lines 93-102, etc.

2022-03-07 17:50 UTC, colemanliyah commented on optical_rotation_scrapping/attributes.csv
>  3032576,+230
For these molecules, their opr value just happened to be the same. For instance, in the case of the molecule in row 13 (https://pubchem.ncbi.nlm.nih.gov/compound/3032576#section=Optical-Rotation) and 14 (https://pubchem.ncbi.nlm.nih.gov/compound/3036746#section=Optical-Rotation) they had a few opr values listed but I take the one that was recorded at a temperature closest to room temperature. But the values for both seem to be the same.

2022-03-07 19:40 UTC, rgerkin commented on optical_rotation_scrapping/attributes.csv
>  3032576,+230
Oh, interesting.  It turns out it is the same molecule but with different PubChem IDs.  I think this isn't possible anymore (if they identified the same molecule they would just update the original entry) but maybe back in the day they weren't so good about catching this.

2022-03-07 19:40 UTC, merged