snitz et al 2019 added
pyrfume/pyrfume-data pull request #74
Opened 2022-03-03 15:31 UTC by TGouldBates

Notes:

1. I've only processed data for individual odorants and omitted mixtures since mixtures won't have unique CID
2. The descriptor terms were slightly different between datasets for SmellSpace and control groups; I can make uniform is that is preferable.

2022-03-07 19:47 UTC, rgerkin requested changes
Minor changes requested.

2022-03-07 19:47 UTC, rgerkin commented on snitz et al 2019/behavior_1.csv
> +CID,UID,SessionNumber,Pleasant,Volatile,WeakStrong,Bitter,Chemical,Spice,Sweet,FreshRotten,CleanDirty,Burnt,Fruity,Develops,Garlic
SessionNumber column is always blank.  This information might be useful for conducting test/retest reliability analyses.  Can you get it in there?

2022-03-07 19:47 UTC, rgerkin commented on snitz et al 2019/behavior_1.csv
> +CID,UID,SessionNumber,Pleasant,Volatile,WeakStrong,Bitter,Chemical,Spice,Sweet,FreshRotten,CleanDirty,Burnt,Fruity,Develops,Garlic
Or if there is no sessionnumber for this file can you drop the column?

2022-03-07 19:47 UTC, rgerkin commented on snitz et al 2019/manifest.toml
> +"odorants.csv" = "Info on odorants used in study; manualy scraped from Table 1 in published manuscript"
All the raw files here are inside a subdirectory "published_data".  So either you should include that in the path here (i.e. "published_data/odorants.csv") or move them out of the published_data directory into the root directory.  Same for the other "raw" files below.

2022-03-08 01:25 UTC, rgerkin commented
Actually uniformity of terms would also be helpful.  Do the terms in the two files differ in ways that reflect what was actually asked of the users or is it more of a mistake on the part of whoever put the raw files together?

2022-03-09 17:15 UTC, TGouldBates commented on snitz et al 2019/behavior_1.csv
> +CID,UID,SessionNumber,Pleasant,Volatile,WeakStrong,Bitter,Chemical,Spice,Sweet,FreshRotten,CleanDirty,Burnt,Fruity,Develops,Garlic
There was no "session number" for the SmellSpace participant data, so I'll just remove the column.

2022-03-10 16:19 UTC, rgerkin requested changes
A few more changes.

2022-03-10 16:19 UTC, rgerkin commented on snitz_2019/published_data/odorants.csv
> +﻿,Odor code,Name,CAS number,(V/V in IPM),CID,Number of subjects,Intensity ratings
Does the number in the current, unlabeled index (left-most column, numbers 1, 2, 3, etc.) appear anywhere else in the data set?  If only Odor code is used as an identifier, you should delete the current index and set CID to be the index.  Or if CID is non-unique in this dataset (which would happen if all of these were not unique, identifiable, single molecules) you can make Odor code the index.

2022-03-10 16:19 UTC, rgerkin commented on snitz_2019/published_data/odorants.csv
> +1 ,JX ,Laevo-fenchone ,7787-20-4 ,7.60% ,14525,985 ,62.6305 
It looks like the separator here is ", ", i.e. comma with a space, which is non-standard.  Can you change to just "," so the default loader will work with it easily? It will load with the space, but then someone would have to strip a space from every string, numbers would become strings, etc.

2022-03-10 16:19 UTC, rgerkin commented on snitz_2019/published_data/odorants.csv
> +2 ,QB ,Isoamyl acetate ,123-92-2 ,25.00% ,31276,985 ,48.0234 
It's easier to deal with % concentrations as floats rather than strings, so can you strip the % sign from that column so they can all be loaded as floats?

2022-03-11 15:43 UTC, merged