Arshamian 2022 added
pyrfume/pyrfume-data pull request #88
Opened 2022-04-04 17:44 UTC by TGouldBates

2022-04-05 15:35 UTC, rgerkin commented
@TGouldBates Looks like this PR still has the files from Mayhew as well.  Can you de-stage them from this PR?

2022-04-05 16:21 UTC, rgerkin commented on arshamian_2022/manifest.toml
> +data/All data intensity.txt = "Ordor intensity rankings from global participants"
@TGouldBates Extremely minor: the .toml file will not correctly parse if the keys have any spaces in them.  I'll handle this (it's a quick edit for me) but in the future go ahead and change file names to add underscores so there are no spaces.

2022-04-05 16:23 UTC, TGouldBates commented on arshamian_2022/manifest.toml
> +data/All data intensity.txt = "Ordor intensity rankings from global participants"
Got it, no problem.

2022-04-05 16:25 UTC, TGouldBates commented
No problem.

I removed the Mayhew directory from my Arshamian branch. Did that percolate
through to the PR so that you only see the Arshamian directory in that PR?

On Tue, Apr 5, 2022 at 12:22 PM Richard C Gerkin ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In arshamian_2022/manifest.toml
> <https://github.com/pyrfume/pyrfume-data/pull/88#discussion_r843010449>:
>
> > @@ -0,0 +1,20 @@
> +# Manifest for Arshamian et al 2022
> +[source]
> +doi = "10.1101/2021.03.01.433367"
> +title = "The perception of odor pleasantness is shared across cultures."
> +authors = "A. Arshamian, R.C. Gerkin, N. Kruspe, E. Wnuk, S. Floyd, C. O'Meara, G. Garrido Rodriguez, J. Lundstrom, J.D. Mainland, A. Majid"
> +extra = ""
> +
> +[raw]
> +data/All data intensity.txt = "Ordor intensity rankings from global participants"
>
> @TGouldBates <https://github.com/TGouldBates> Extremely minor: the .toml
> file will not correctly parse if the keys have any spaces in them. I'll
> handle this (it's a quick edit for me) but in the future go ahead and
> change file names to add underscores so there are no spaces.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pyrfume/pyrfume-data/pull/88#pullrequestreview-932171073>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMR2YW2W2DFGUTXMJ2FL3FLVDRSDFANCNFSM5SQIRDIA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-05 16:28 UTC, rgerkin requested changes

2022-04-05 16:28 UTC, rgerkin commented on arshamian_2022/behavior_2.csv
> +ParticipantID,1) Odor intensity (most intense),2) Odor intensity,3) Odor intensity,4) Odor intensity,5) Odor intensity,6) Odor intensity,7) Odor intensity,8) Odor intensity,9) Odor intensity,10) Odor
- Can you format this file to use the CIDs.  Then molecules.csv can be used to decode the rest.
- Can you retitle the columns to just be the ranks 1-10, or "Rank 1", "Rank 2", etc.?  If you think it is unclear the .toml file can be used to give more description.  The goal in these processed files is to retain the information but in a compact form, not necessarily to retain the exact text used by the original data collectors.

2022-04-05 16:28 UTC, rgerkin commented on arshamian_2022/behavior_1.csv
> +CID,ParticipantID,Ranking,Subsistence
- Subsistence is a property of the participant and should go in the subjects.csv and not in behavior files.

2022-04-05 16:28 UTC, rgerkin commented on arshamian_2022/behavior_3.csv
> +CID,RaterID,Rep1,Rep2
The raters here are still subjects (for a different experiment) so give them ParticipantIDs in subjects.csv and then use those IDs here.  You can leave their subsistence column blank, and their group can be "Philadelphia".

2022-04-06 16:48 UTC, TGouldBates commented
Got it. Changes implemented and pushed.

On Tue, Apr 5, 2022 at 12:28 PM Richard C Gerkin ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In arshamian_2022/behavior_2.csv
> <https://github.com/pyrfume/pyrfume-data/pull/88#discussion_r843016948>:
>
> > @@ -0,0 +1,126 @@
> +ParticipantID,1) Odor intensity (most intense),2) Odor intensity,3) Odor intensity,4) Odor intensity,5) Odor intensity,6) Odor intensity,7) Odor intensity,8) Odor intensity,9) Odor intensity,10) Odor intensity (least intense/weakest)
>
>
>    - Can you format this file to use the CIDs. Then molecules.csv can be
>    used to decode the rest.
>    - Can you retitle the columns to just be the ranks 1-10, or "Rank 1",
>    "Rank 2", etc.? If you think it is unclear the .toml file can be used to
>    give more description. The goal in these processed files is to retain the
>    information but in a compact form, not necessarily to retain the exact text
>    used by the original data collectors.
>
> ------------------------------
>
> In arshamian_2022/behavior_1.csv
> <https://github.com/pyrfume/pyrfume-data/pull/88#discussion_r843018260>:
>
> > @@ -0,0 +1,2831 @@
> +CID,ParticipantID,Ranking,Subsistence
>
>
>    - Subsistence is a property of the participant and should go in the
>    subjects.csv and not in behavior files.
>
> ------------------------------
>
> In arshamian_2022/behavior_3.csv
> <https://github.com/pyrfume/pyrfume-data/pull/88#discussion_r843021101>:
>
> > @@ -0,0 +1,101 @@
> +CID,RaterID,Rep1,Rep2
>
> The raters here are still subjects (for a different experiment) so give
> them ParticipantIDs in subjects.csv and then use those IDs here. You can
> leave their subsistence column blank, and their group can be "Philadelphia".
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pyrfume/pyrfume-data/pull/88#pullrequestreview-932179045>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMR2YW72NOG2I7NSZ4HWYZDVDRS2RANCNFSM5SQIRDIA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-07 18:31 UTC, closed without merging