Ma 2012 added
pyrfume/pyrfume-data pull request #91
Opened 2022-04-07 19:06 UTC by TGouldBates

2022-04-11 20:51 UTC, rgerkin requested changes
See inline comments.  Also, I think behavior_2.csv may have the same issue with no index column name.

2022-04-11 20:51 UTC, rgerkin commented on ma_2012/behavior_1.csv
> +CID,Dorsal Response
Let's change None, *, **, *** to 0, 1, 2, 3.  The goal is to make this as ML-ready as possible.  You can document this in manifest.toml.

2022-04-11 20:51 UTC, rgerkin commented on ma_2012/artifact_mask.csv
> +,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA051
The index column should have a title.  The fact that this starts with a comma says that the index has no title.  Whatever the index column is encoding, give the index column a title suggestive if that.

2022-04-15 00:15 UTC, TGouldBates commented
Re no index in behavior_2.csv and artifact_mask.csv: I think the issue here
is just that in the multiline header for the columns, that first position
is blank because the index is on the third line when panda exports. If you
scroll down a bit, you'll see that both files have an index named "Glom".
And when I download from the raw view on GitHub and then open as a .csv
they both show the idex.

On Mon, Apr 11, 2022 at 4:51 PM Richard C Gerkin ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> See inline comments. Also, I think behavior_2.csv may have the same issue
> with no index column name.
> ------------------------------
>
> In ma_2012/behavior_1.csv
> <https://github.com/pyrfume/pyrfume-data/pull/91#discussion_r847723502>:
>
> > @@ -0,0 +1,198 @@
> +CID,Dorsal Response
>
> Let's change None, *, **, *** to 0, 1, 2, 3. The goal is to make this as
> ML-ready as possible. You can document this in manifest.toml.
> ------------------------------
>
> In ma_2012/artifact_mask.csv
> <https://github.com/pyrfume/pyrfume-data/pull/91#discussion_r847724274>:
>
> > @@ -0,0 +1,115 @@
> +,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0512,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0513,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA0409,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA12v2,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-right,GIA11-ri [...]

2022-05-02 17:30 UTC, rgerkin requested changes

2022-05-02 17:30 UTC, rgerkin commented on ma_2012/manifest.toml
> +artifact_mask.csv = "Same shape as behavior_2.csc; 0 indicates data that is subject to 'motion artifact' and was not included in published analysis."
Typo csc -> csv.

2022-05-02 17:30 UTC, rgerkin commented on ma_2012/manifest.toml
> +behavior_2.csv = "DeltaF/F data for each imaging experiment."
I don't understand the format of this file.  What is happening here?

2022-05-02 17:30 UTC, rgerkin commented on ma_2012/manifest.toml
> +odor_abbr.csv = "Mapping of published odor abbreviations to CIDs"
Double-checking: was every odorant used her monomolecular and resolvable to a CID?  If there are any that aren't, you will want to swap the columns in this file (and call it identifiers.csv) and then use the abbreviations instead of CIDs in the behavior files for completeness.  But if everything has a CID, then the current setup is fine.

2022-05-02 17:30 UTC, rgerkin commented on ma_2012/manifest.toml
> +odor_conc.csv = "Concentration of odorants used in each experiment, expressed as percentage of saturated vapor. Index maps to integers in odor abbrevations in behavior_2.csv column headings."
I don't understand the mapping.

2022-05-23 23:16 UTC, merged